version: '3'
services:
# Responsible for hosting devlop server
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - "4001:4001"
    volumes:
      - /app/node_modules
      - .:/app
# # Responsible for hosting test
#   tests:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev 
#     volumes:
#       - /app/node_modules
#       - .:/app
#     command: ["npm", "run", "test"]